[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "io"
    version = "1.2.19"
    path = "./lib/ballerina-io-1.2.19.jar"
    groupId = "ballerina"
    modules = ["io"]
