[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "transactions"
    version = "1.2.19"
    path = "./lib/ballerina-transactions-1.2.19.jar"
    groupId = "ballerina"
    modules = ["transactions"]
