[project]
org-name = "ballerina"
version = "0.8.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "observability"
    version = "1.2.19"
    path = "./lib/ballerina-observability-1.2.19.jar"
    groupId = "ballerina"
    modules = ["observe"]
