[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "xslt"
    version = "1.2.19"
    path = "./lib/ballerina-xslt-1.2.19.jar"
    groupId = "ballerina"
    modules = ["xslt"]

    [[platform.libraries]]
    artifactId = "axiom-api"
    version = "1.2.22"
    path = "./lib/axiom-api-1.2.22.jar"
    groupId = "org.apache.ws.commons.axiom"
    modules = ["xslt"]

    [[platform.libraries]]
    artifactId = "axiom-impl"
    version = "1.2.22"
    path = "./lib/axiom-impl-1.2.22.jar"
    groupId = "org.apache.ws.commons.axiom"
    modules = ["xslt"]
