[project]
org-name = "ballerina"
version = "0.7.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "filepath"
    version = "1.2.19"
    path = "./lib/ballerina-filepath-1.2.19.jar"
    groupId = "ballerina"
    modules = ["filepath"]
