[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "math"
    version = "1.2.19"
    path = "./lib/ballerina-math-1.2.19.jar"
    groupId = "ballerina"
    modules = ["math"]
