[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "runtime-api"
    version = "1.2.19"
    path = "./lib/ballerina-runtime-api-1.2.19.jar"
    groupId = "ballerina"
    modules = ["runtime-api"]
