[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "time"
    version = "1.2.19"
    path = "./lib/ballerina-time-1.2.19.jar"
    groupId = "ballerina"
    modules = ["time"]
