[project]
org-name = "ballerina"
version = "0.6.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "system"
    version = "1.2.19"
    path = "./lib/ballerina-system-1.2.19.jar"
    groupId = "ballerina"
    modules = ["system"]
