[project]
org-name = "ballerina"
version = "1.1.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "task"
    version = "1.2.19"
    path = "./lib/ballerina-task-1.2.19.jar"
    groupId = "ballerina"
    modules = ["task"]

    [[platform.libraries]]
    artifactId = "quartz"
    version = "2.3.2"
    path = "./lib/quartz-2.3.2.jar"
    groupId = "org.quartz-scheduler"
    modules = ["task"]
