[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "jdbc"
    version = "1.2.19"
    path = "./lib/ballerina-jdbc2-1.2.19.jar"
    groupId = "ballerina"
    modules = ["jdbc"]

    [[platform.libraries]]
    artifactId = "jdbc"
    version = "1.2.19"
    path = "./lib/ballerina-sql-1.2.19.jar"
    groupId = "ballerina"
    modules = ["jdbc"]